import type { Event, Ticket } from "@/types/event"

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Jazz Night Festival 2024",
    type: "concert",
    date: "2024-07-15",
    time: "19:00",
    location: "Jakarta Convention Center",
    capacity: 5000,
    participants: 3200,
    description:
      "Experience the best jazz musicians from around the world in this spectacular night festival. Featuring international and local artists performing classic and contemporary jazz pieces.",
    image: "/placeholder.svg?height=400&width=600",
    ticketTypes: [
      {
        id: "1",
        name: "Regular",
        price: 150000,
        quota: 3000,
        available: 1200,
        features: ["General Admission", "Standing Area", "Basic Facilities"],
        color: "regular",
      },
      {
        id: "2",
        name: "VIP",
        price: 350000,
        quota: 1500,
        available: 800,
        features: ["Reserved Seating", "VIP Lounge Access", "Complimentary Drinks", "Meet & Greet"],
        color: "vip",
      },
      {
        id: "3",
        name: "VVIP",
        price: 750000,
        quota: 500,
        available: 0,
        features: ["Premium Seating", "Exclusive Lounge", "Gourmet Dining", "Artist Meet & Greet", "Merchandise"],
        color: "vvip",
      },
    ],
  },
  {
    id: "2",
    title: "Modern Art Exhibition",
    type: "exhibition",
    date: "2024-07-20",
    time: "10:00",
    location: "National Gallery",
    capacity: 2000,
    participants: 1500,
    description:
      "Discover contemporary masterpieces from renowned artists worldwide. This exhibition showcases the evolution of modern art through interactive displays and guided tours.",
    image: "/placeholder.svg?height=400&width=600",
    ticketTypes: [
      {
        id: "4",
        name: "Regular",
        price: 75000,
        quota: 1500,
        available: 500,
        features: ["General Access", "Audio Guide", "Exhibition Catalog"],
        color: "regular",
      },
      {
        id: "5",
        name: "VIP",
        price: 150000,
        quota: 400,
        available: 200,
        features: ["Priority Access", "Guided Tour", "Workshop Access", "Exclusive Catalog"],
        color: "vip",
      },
      {
        id: "6",
        name: "VVIP",
        price: 300000,
        quota: 100,
        available: 50,
        features: ["Private Tour", "Artist Meet", "Premium Catalog", "Exclusive Preview", "Refreshments"],
        color: "vvip",
      },
    ],
  },
  {
    id: "3",
    title: "Tech Innovation Seminar",
    type: "seminar",
    date: "2024-07-25",
    time: "09:00",
    location: "Grand Ballroom Hotel Indonesia",
    capacity: 1000,
    participants: 750,
    description:
      "Join industry leaders discussing the future of technology, AI innovations, and digital transformation strategies for businesses in the modern era.",
    image: "/placeholder.svg?height=400&width=600",
    ticketTypes: [
      {
        id: "7",
        name: "Regular",
        price: 200000,
        quota: 700,
        available: 250,
        features: ["Seminar Access", "Digital Materials", "Certificate"],
        color: "regular",
      },
      {
        id: "8",
        name: "VIP",
        price: 400000,
        quota: 250,
        available: 100,
        features: ["Premium Seating", "Networking Session", "Lunch Included", "Speaker Meet"],
        color: "vip",
      },
      {
        id: "9",
        name: "VVIP",
        price: 800000,
        quota: 50,
        available: 25,
        features: [
          "Executive Seating",
          "Private Networking",
          "Gourmet Lunch",
          "One-on-One Speaker Session",
          "Premium Materials",
        ],
        color: "vvip",
      },
    ],
  },
]

export const mockTickets: Ticket[] = [
  {
    id: "T001",
    eventId: "1",
    eventTitle: "Jazz Night Festival 2024",
    ticketType: "VIP",
    quantity: 2,
    totalPrice: 700000,
    purchaseDate: "2024-06-15",
    eventDate: "2024-07-15",
    status: "active",
    qrCode: "QR123456789",
  },
  {
    id: "T002",
    eventId: "2",
    eventTitle: "Modern Art Exhibition",
    ticketType: "Regular",
    quantity: 1,
    totalPrice: 75000,
    purchaseDate: "2024-06-10",
    eventDate: "2024-07-20",
    status: "active",
    qrCode: "QR987654321",
  },
]
